In [289]:
# Camila Losada - 05/02/2025

## Example on how to use BhvData structure

In [290]:
# Import libraries
from ephysvibe.structures.bhv_data import BhvData
from ephysvibe.task.task_constants import EVENTS_B1
import numpy as np
from matplotlib import pyplot as plt

import platform
import glob

In [291]:
if platform.system() == 'Linux':
    basepath = '/envau/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure'
elif platform.system() == 'Windows':
    basepath = '//envau_cifs.intlocal.univ-amu.fr/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure'

In [292]:
area='lip'
subpath = f'/session_struct/bhv'
path_list = glob.glob(f'{basepath}{subpath}/*')
path_list[:3]

['//envau_cifs.intlocal.univ-amu.fr/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure/session_struct/bhv\\2022-11-22_10-59-03_Riesling_e1_r1_bhv.h5',
 '//envau_cifs.intlocal.univ-amu.fr/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure/session_struct/bhv\\2023-10-06_10-38-57_Riesling_e1_r1_bhv.h5',
 '//envau_cifs.intlocal.univ-amu.fr/work/invibe/USERS/IBOS/data/Riesling/TSCM/OpenEphys/new_structure/session_struct/bhv\\2022-11-28_10-23-27_Riesling_e1_r1_bhv.h5']

In [ ]:
# filepath = "/2023-03-16_10-20-01_Riesling_e1_r1_bhv.h5" 
# bhv = BhvData.from_python_hdf5(f'{basepath}{subpath}{filepath}') # read bhv data
bhv = BhvData.from_python_hdf5(path_list[0])

In [359]:
bhv.__dict__.keys()

dict_keys(['block', 'code_numbers', 'code_times', 'condition', 'eye_ml', 'fix_fp_t_time', 'fix_fp_post_t_time', 'fix_fp_pre_t_time', 'fix_close', 'fix_far', 'iti', 'stim_match', 'pos_code', 'position', 'reward_plus', 'test_distractor', 'test_stimuli', 'sample_id', 'stim_total', 'trial_error', 'closeexc', 'delay_time', 'excentricity', 'farexc', 'fix_post_sacc_blank', 'fix_time', 'fix_window_radius', 'idletime3', 'max_reaction_time', 'rand_delay_time', 'reward_dur', 'sample_time', 'stay_time', 'test_time', 'wait_for_fix', 'date_time', 'subject', 'experiment', 'recording', 'code_samples', 'end_trials', 'start_trials'])

In [360]:
# General information about the session
print(f'subject: {bhv.subject}')
print(f'date_time: {bhv.date_time}')

subject: Riesling
date_time: 2022-11-22_10-59-03


In [361]:
# Behavioural information
print(f'block: {bhv.block}')
mask_b1 = bhv.block==1 # DMTS
mask_b2 = bhv.block==2 # Saccade
print(f'Number of trials: {len(bhv.block)}')
print(f'Number of trials in block 1: {np.sum(mask_b1)}')
print(f'Number of trials in block 2: {np.sum(mask_b2)}')
## Check number of correct trials (error = 0)
mask_err0 = bhv.trial_error==0
print(f'Number of correct trials: {np.sum(mask_err0)}')
print(f'Number of correct trials in block 1: {np.sum(np.logical_and(mask_err0,mask_b1))}')
print(f'Number of correct trials in block 2: {np.sum(np.logical_and(mask_err0,mask_b2))}')

block: [2. 2. 2. ... 1. 1. 1.]
Number of trials: 1412
Number of trials in block 1: 1308
Number of trials in block 2: 104
Number of correct trials: 654
Number of correct trials in block 1: 574
Number of correct trials in block 2: 80


In [362]:
ntr = 5
## Block 2: saccade
print(f'possible samples: {np.unique(bhv.sample_id[mask_b2])}')
print(f'possible sample location: {np.unique(bhv.pos_code[mask_b2])}')
print(f'\ninformation about the first {ntr} trials:')
print(f'sample location {bhv.pos_code[mask_b2].shape}: {bhv.pos_code[mask_b2][:ntr]}')
print(f'events code {bhv.code_numbers[mask_b2].shape}: \n{bhv.code_numbers[mask_b2][:ntr]}')
print(f'events time {bhv.code_samples[mask_b2].shape}: \n{bhv.code_samples[mask_b2][:ntr]}') # All trials are aligned to start trial (code 9)

possible samples: [nan]
possible sample location: [120. 121. 122. 123. 124. 125. 126. 127.]

information about the first 5 trials:
sample location (104,): [122. 121. 124. 122. 126.]
events code (104, 20): 
[[  9.  35.   8.  37. 122.  38.  36.  10.  10.  10.  40.  56.  18.  nan
   nan  nan  nan  nan  nan  nan]
 [  9.  35.   8.  50.  36.  18.  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan]
 [  9.  35.   8.  37. 124.  38.  36.  10.  10.  10.  40.  56.  18.  nan
   nan  nan  nan  nan  nan  nan]
 [  9.  35.   8.  37. 122.  38.  36.  10.  10.  10.  40.  56.  18.  nan
   nan  nan  nan  nan  nan  nan]
 [  9.  35.   8.  37. 126.  38.  51.  36.  38.  18.  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan]]
events time (104, 20): 
[[ 9707.  9722.  9860. 10216. 10217. 10334. 11346. 11657. 11959. 11969.
  12028. 12233. 12234.    nan    nan    nan    nan    nan    nan    nan]
 [13736. 13746. 13799. 13802. 13816. 13818.    nan    nan    nan    nan
     nan    nan    nan    n

In [363]:
## Block 1: DMTS
print(f'possible samples: {np.unique(bhv.sample_id[mask_b1])}')
print(f'possible sample location: {np.unique(bhv.pos_code[mask_b1])}')
print(f'\ninformation about the first {ntr} trials:')
print(f'sample id {bhv.sample_id[mask_b1].shape}: {bhv.sample_id[mask_b1][:ntr]}')
print(f'test stimuli {bhv.test_stimuli[mask_b1].shape}: \n{bhv.test_stimuli[mask_b1][:ntr]}')
print(f'test distractor {bhv.test_distractor[mask_b1].shape}: \n{bhv.test_distractor[mask_b1][:ntr]}')
print(f'events code {bhv.code_numbers[mask_b1].shape}: \n{bhv.code_numbers[mask_b1][:ntr]}')
print(f'events time {bhv.code_samples[mask_b1].shape}: \n{bhv.code_samples[mask_b1][:ntr]}') # All trials are aligned to 1000 ms before the start of the trial

possible samples: [ 0. 11. 15. 51. 55.]
possible sample location: [-1.  1.]

information about the first 5 trials:
sample id (1308,): [ 0. 55. 51. 51.  0.]
test stimuli (1308, 5): 
[[52. nan nan nan nan]
 [58. 74. 45. 52. 55.]
 [52. nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
test distractor (1308, 5): 
[[83. nan nan nan nan]
 [88. 22. 11. 63. 76.]
 [66. nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
events code (1308, 20): 
[[ 9.  7. 35.  8. 23. 24. 25. 97. 36. 26. 18. nan nan nan nan nan nan nan
  nan nan]
 [ 9.  7. 35.  8. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33.  4. 36. 34.
  96. 18.]
 [ 9.  7. 35.  8. 23. 24. 25. 97. 36. 26. 18. nan nan nan nan nan nan nan
  nan nan]
 [ 9.  7. 35.  8. 23.  4. 36. 24. 18. nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 9.  7. 35.  8. 23. 24. 97. 36. 18. nan nan nan nan nan nan nan nan nan
  nan nan]]
events time (1308, 20): 
[[396805. 396814. 396820. 396994. 397208. 397667. 398090. 398105. 398114.
  398114.

### Evaluate performance in DMTS

### Start with whether there was an error in the task design

In [364]:
from ephysvibe.task.control import correct_task_errors

In [365]:
trial_errors = bhv.trial_error[mask_b1].copy()  # Working copy of trial errors
stim_match = bhv.stim_match[mask_b1]
test_stimuli = bhv.test_stimuli[mask_b1]
sample_ids = bhv.sample_id[mask_b1]
task_errors = correct_task_errors(trial_errors,stim_match,test_stimuli,sample_ids)
idx = np.where(trial_errors!=task_errors)[0]
print(trial_errors[idx])
print(task_errors[idx])
print(test_stimuli[idx])
print(sample_ids[idx])

INFO:ephysvibe.task.control:No errors found.


[]
[]
[]
[]


#### Now we can define a matrix indicating the position of the hits,miss,FA and CR

In [366]:
from ephysvibe.task.bhv_eval import compute_performance
test_stimuli = bhv.test_stimuli[mask_b1]
sample_id   = bhv.sample_id[mask_b1]
perf=compute_performance(test_stimuli,sample_id, task_errors)

In [367]:
np.sum(task_errors==8)+np.sum(task_errors==6)

np.int64(98)

In [373]:
np.unique(sample_id[task_errors==6],return_counts=True)

(array([ 0., 11., 15., 51., 55.]), array([ 3, 14, 14, 20, 11]))

In [374]:
np.unique(test_stimuli[perf==4],return_counts=True)

(array([11., 14., 15., 16., 17., 18., 21., 25., 37., 41., 43., 51., 53.,
        55., 56., 57., 58., 61., 62., 65., 71., 75., 81., 85.]),
 array([4, 2, 3, 1, 1, 3, 1, 3, 1, 4, 1, 2, 2, 6, 3, 1, 2, 3, 2, 3, 3, 1,
        8, 2]))